before:
  hooks:
    - go mod download
builds:
  - id: tdsh-api
    main: ./cmd/tdsh-api/tdsh-api.go
    binary: tdsh-api
    goos:
      - linux
    goarch:
      - amd64
  - id: tdsh-crawler
    main: ./cmd/tdsh-crawler/tdsh-crawler.go
    binary: tdsh-crawler
    goos:
      - linux
    goarch:
      - amd64
  - id: tdsh-extractor
    main: ./cmd/tdsh-extractor/tdsh-extractor.go
    binary: tdsh-extractor
    goos:
      - linux
    goarch:
      - amd64
  - id: tdsh-scheduler
    main: ./cmd/tdsh-scheduler/tdsh-scheduler.go
    binary: tdsh-scheduler
    goos:
      - linux
    goarch:
      - amd64
  - id: trandoshanctl
    main: ./cmd/trandoshanctl/trandoshanctl.go
    binary: trandoshanctl
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
release:
  prerelease: true