name: trandoshan
version: git
summary: Distributed dark web crawler.
description: |
  Fast, highly configurable, distributed dark web crawler designed to run on the cloud.
confinement: strict
license: GPL-3.0
grade: stable
base: core18
parts:
  trandoshan:
    plugin: go
    go-importpath: github.com/creekorful/trandoshan
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  api:
    command: bin/tdsh-api
    plugs:
      - network
  crawler:
    command: bin/tdsh-crawler
    plugs:
      - network
  feeder:
    command: bin/tdsh-feeder
    plugs:
      - network
  persister:
    command: bin/tdsh-persister
    plugs:
      - network
  scheduler:
    command: bin/tdsh-scheduler
    plugs:
      - network
