version: '3'

services:
  nats:
    image: nats:2.1.9-alpine3.12
  torproxy:
    image: dperson/torproxy:latest
  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.10.1
    depends_on:
      - elasticsearch
    ports:
      - 15004:5601
  crawler:
    image: creekorful/tdsh-crawler:latest
    command: --log-level debug --nats-uri nats --tor-uri torproxy:9050
    restart: always
    depends_on:
      - nats
      - torproxy
  scheduler:
    image: creekorful/tdsh-scheduler:latest
    command: --log-level debug --nats-uri nats --api-uri http://api:8080 --api-login scheduler:ZjDXeaLGj4EEUGu6
    restart: always
    depends_on:
      - nats
      - api
  extractor:
    image: creekorful/tdsh-extractor:latest
    command: --log-level debug --nats-uri nats --api-uri http://api:8080 --api-login extractor:hWx2KsrhWVQb5vxg
    restart: always
    depends_on:
      - nats
      - api
  api:
    image: creekorful/tdsh-api:latest
    command: --log-level debug --nats-uri nats --elasticsearch-uri http://elasticsearch:9200 --signing-key K==M5RsU_DQa4_XSbkX?L27s^xWmde25 --users extractor:hWx2KsrhWVQb5vxg --users scheduler:ZjDXeaLGj4EEUGu6 --users demo:demo
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 15005:8080

volumes:
  esdata:
    driver: local
