name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go: [ 1.15 ]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: |
          go get -v golang.org/x/lint/golint
          go get -v github.com/golang/mock/mockgen@v1.4.4

      - name: Lint source code
        run: golint -set_exit_status ./...

      - name: Run Tests
        run: |
          go generate ./...
          go test -race --coverprofile=coverage.coverprofile --covermode=atomic -v ./...

      - name: Update go report card
        if: success() && matrix.os == 'ubuntu-latest'
        continue-on-error: true
        uses: creekorful/goreportcard-action@v1.0